apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: dynamic-trust-isolation
  namespace: banking
spec:
  selector:
    matchLabels:
      app: account-service
  action: DENY
  rules:
  - from:
    - source:
        namespaces: ["banking"]
